const assert = require('node:assert/strict');
const { test } = require('node:test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const ts = require('typescript');
const knex = require('knex');
const root = path.resolve(__dirname, '..');

function loadSource(file, db, cache = new Map(), oss = null) {
  file = path.resolve(file);
  if (cache.has(file)) return cache.get(file).exports;
  const module = { exports: {} }; cache.set(file, module);
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: {
    module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true,
  }, fileName: file }).outputText;
  new Function('require', 'module', 'exports', code)(name => {
    if (name === '@/utils/db') return { db };
    if (name === '@/utils') return { oss, vendor: { getModelList: async () => ['vision','vision-v2'].map(modelName => ({ modelName, type: 'text', supports: { image_input: true } })), getCode: () => 'vision-adapter-v1' }, Ai: { Text: model => ({ trackedSession: async () => { if (oss.sessionError) throw oss.sessionError; oss.sessionCount=(oss.sessionCount||0)+1; return { modelReference: model, invokeObject: async input => {
      oss.modelCalls.push({ model, ...input, method: 'invokeObject' });
      if (model === 'fake:local') {
        const next=oss.skillResponses?.shift();
        if (next instanceof Error) throw next;
        return {object: next ?? oss.proposalOutput};
      }
      oss.visionCalls++;
      if (oss.visionFailure) throw oss.visionFailure;
      if (oss.modelError) throw Error('provider call failed');
      return { object: oss.visionResult ?? { summary: 'A dark blue image with a bright logo', dominantColors: ['deep blue'], visibleText: ['DreamStream'], uncertainty: [] } };
    }, invoke: async input => {
      oss.modelCalls.push({ model, ...input, method: input.output ? 'invokeJson' : 'invokeText' });
      const next=input.output ? oss.skillResponses?.shift() : oss.studioResponses?.shift();
      if (next instanceof Error) throw next;
      if (oss.modelError) throw Error('provider call failed');
      if (!input.output) return { text: next === undefined ? JSON.stringify(oss.proposalOutput) : next };
      return { output: next ?? oss.proposalOutput };
    } }; }, invoke: async input => {
      oss.modelCalls.push({ model, ...input });
      if (model.startsWith('fake:vision')) throw Error('Vision must use structured output');
      if (oss.textError) throw Error('text provider failed');
      const next=oss.skillResponses?.shift();
      if (next instanceof Error) throw next;
      return { text: 'I can discuss the observed image in this project.', output: next ?? oss.proposalOutput };
    } }) } };
    if (name === '@/utils/getPath') return value => path.join(oss.testDir,...(Array.isArray(value)?value:[value||'v04-conversation']));
    if (name === '@/services/modelPreset') { oss.ModelConfigError ??= class ModelConfigError extends Error {}; return { ModelConfigError: oss.ModelConfigError, requireModel: async (_projectId, slot) => { if (slot === 'vision' && !oss.visionModel || slot === 'text' && oss.textModelUnavailable) throw new oss.ModelConfigError('model unavailable'); return slot === 'vision' ? oss.visionModel : 'fake:local'; }, resolveModels: async () => ({ models: { vision: oss.visionModel } }) }; }
    if (name === '@/utils/agent/memory') return class { async get() { if (oss.contextFailure) throw oss.contextFailure; return {rag:[], summaries:[]}; } };
    if (name === '@/utils/agent/embedding') return { getEmbedding: async () => [] };
    if (name === '@/services/assetUploadSource') return { recordAssetUpload: async (trx, source) => {
      const asset = await trx('o_assets').where({ id: source.assetId, projectId: source.projectId, imageId: source.imageId }).first();
      const image = await trx('o_image').where({ id: source.imageId, assetsId: source.assetId, filePath: source.filePath }).first();
      if (!asset || !image || image.model) throw Error('UPLOAD_SOURCE_INVALID');
      await trx('o_assetUploadSource').insert(source);
    } };
    if (name === '@/services/advertisementAssetPlan') return { readAssetPlanInTransaction: async (trx, scope) => ({items: (await trx('o_advertisementAssetPlan').where(scope).orderBy('position')).map(row => ({...row,bindingValid:row.assetId != null}))}), assertAssetPlanBinding: async (trx, scope, item) => {
      const asset = await trx('o_assets').where({ id: item.assetId, projectId: scope.projectId, scriptId: scope.scriptId }).first();
      const linked = asset && await trx('o_scriptAssets').where({ scriptId: scope.scriptId, assetId: asset.id }).first();
      if (!asset || !linked) throw Error('ASSET_SCOPE');
      if (item.sourcePolicy === 'REAL_REQUIRED') {
        const image = await trx('o_image').where({ id: asset.imageId, assetsId: asset.id, state: '已完成' }).first();
        const receipt = image && await trx('o_assetUploadSource').where({ assetId: asset.id, imageId: image.id, filePath: image.filePath }).first();
        if (!receipt || image.model) throw Error('REAL_SOURCE_REQUIRED');
      }
    } };
    if (name === '@/services/orchestrator/videoProductionProfile') return { advertisement001eDefinition: {} };
    if (name === '@/services/orchestrator/profileDefinition') return { definitionHash: () => 'a'.repeat(64) };
    if (name === '@/lib/advertisementAssetPlanSchema') return { ASSET_PLAN_TABLE: 'o_advertisementAssetPlan' };
    if (name.startsWith('.')) return loadSource(path.resolve(path.dirname(file), name + '.ts'), db, cache, oss);
    return require(name);
  }, module, module.exports);
  return module.exports;
}
async function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'v04-pilot-'));
  const db = knex({ client: 'better-sqlite3', connection: { filename: path.join(dir, 'test.sqlite') }, useNullAsDefault: true });
  const oss = { writeFile: async (p, bytes) => { const target=path.join(dir,'oss',p.replace(/^\//,'')); fs.mkdirSync(path.dirname(target),{recursive:true}); fs.writeFileSync(target,bytes); }, getFile: async p => fs.readFileSync(path.join(dir,'oss',p.replace(/^\//,''))), deleteFile: async p => fs.rmSync(path.join(dir,'oss',p.replace(/^\//,'')),{force:true}) };
  oss.modelCalls=[]; oss.visionCalls=0; oss.visionModel='fake:vision';
  oss.testDir=dir;
  t.after(async () => { await db.destroy(); fs.rmSync(dir, { recursive: true, force: true }); });
  await db.schema.createTable('o_project', x => { x.bigInteger('id').primary(); x.string('projectType'); x.string('type'); x.string('name'); x.text('intro'); x.string('artStyle'); x.string('directorManual'); x.string('videoRatio'); x.string('imageModel'); x.string('videoModel'); x.string('imageQuality'); x.string('mode'); x.integer('userId'); x.bigInteger('createTime'); });
  await db.schema.createTable('o_script', x => { x.increments('id'); x.bigInteger('projectId'); x.string('name'); x.text('content'); x.bigInteger('createTime'); });
  await db.schema.createTable('o_storyboard', x => { x.increments('id'); x.bigInteger('projectId'); x.integer('scriptId'); x.integer('index'); x.text('prompt'); x.integer('duration'); x.text('videoDesc'); x.text('productionSpec'); x.string('state'); x.string('filePath'); x.integer('currentImageAttemptId'); x.integer('activeImageAttemptId'); x.bigInteger('retiredAt'); });
  await db.schema.createTable('o_productionProfileVersion', x => { x.string('profileKey'); x.integer('version'); x.string('status'); x.string('definitionHash'); x.text('definition'); x.bigInteger('createdAt'); x.bigInteger('updatedAt'); x.bigInteger('activatedAt'); x.bigInteger('deprecatedAt'); x.primary(['profileKey','version']); });
  await db.schema.createTable('o_projectProfileBinding', x => { x.bigInteger('projectId').primary(); x.string('profileKey'); x.integer('profileVersion'); x.string('source'); x.bigInteger('createdAt'); x.bigInteger('updatedAt'); });
  await db('o_productionProfileVersion').insert({profileKey:'advertisement',version:2,status:'ACTIVE',definition:'{}',definitionHash:'a'.repeat(64)});
  await db.schema.createTable('o_assets', x => { x.increments('id'); x.bigInteger('projectId'); x.integer('scriptId'); x.integer('imageId'); x.string('name'); x.text('describe'); x.text('prompt'); x.string('type'); x.bigInteger('startTime'); });
  await db.schema.createTable('o_scriptAssets', x => { x.integer('scriptId'); x.integer('assetId'); x.primary(['scriptId','assetId']); });
  await db.schema.createTable('o_image', x => { x.increments('id'); x.integer('assetsId'); x.string('state'); x.string('filePath'); x.string('model'); x.string('type'); });
  await db.schema.createTable('o_assetUploadSource', x => { x.integer('projectId'); x.integer('assetId'); x.integer('imageId'); x.string('filePath'); });
  await db.schema.createTable('o_advertisementAssetPlan', x => { x.bigInteger('projectId'); x.integer('scriptId'); x.string('assetKey'); x.string('name'); x.string('category'); x.integer('required'); x.string('sourcePolicy'); x.integer('assetId'); x.integer('position'); x.primary(['projectId','scriptId','assetKey']); });
  await db.schema.createTable('memories', x => { x.string('id').primary(); x.string('isolationKey'); x.string('type'); x.string('role'); x.text('content'); x.text('embedding'); x.integer('summarized'); x.bigInteger('createTime'); });
  const schema = loadSource(path.join(root,'src/v04/schema.ts'),db);
  await schema.initializeV04Schema(db); await schema.initializeV04Schema(db);
  const cache = new Map();
  return { db, oss, cache, service: loadSource(path.join(root,'src/v04/service.ts'),db,cache,oss), agent: loadSource(path.join(root,'src/v04/agentAttachments.ts'),db,cache,oss) };
}
const {randomUUID,createHash}=require('node:crypto');
const pngHash=b=>createHash('sha256').update(b).digest('hex');
async function editFixture(t){
 const f=await fixture(t);const {db,oss,cache,service}=f;const scope=await service.createPilotProject({name:'Image edit',brief:'A boy',targetDuration:30,aspectRatio:'16:9'},7);
 const png=await require('sharp')({create:{width:32,height:32,channels:3,background:'#527080'}}).png().toBuffer();
 await db('o_v04Asset').insert({projectId:scope.projectId,canonicalKey:'CHAR-001',category:'CHAR',name:'Boy',description:'A boy in sleepwear',sourcePolicy:'AI_ALLOWED',assetKind:'HUMAN_CHARACTER',importance:'CORE',status:'ACTIVE',revision:1,createdAt:1,updatedAt:1});
 const media=new Map();const imageFile=path.join(root,'src/v04/studioDraftImage.ts');cache.set(imageFile,{exports:{getDraftArtifact:async(p,id)=>{const row=await db('o_v04StudioDraftArtifact').where({projectId:p,artifactId:id}).first();if(!row)throw Error('artifact missing');return {bytes:media.get(id),mimeType:'image/png'};},wakeDraftWorker:()=>{}}});
 async function source(role='MAIN_PREVIEW',status='SUCCEEDED',time=1,mode='CHARACTER_TURNAROUND'){
  const id=randomUUID(),artifactId=randomUUID(),out={artifactId,role,mimeType:'image/png',width:32,height:32,fileRef:'/api/v04/studio/artifact/'+scope.projectId+'/'+artifactId};media.set(artifactId,png);
  await db('o_v04StudioAssetDraftJob').insert({id,...scope,canonicalKey:'CHAR-001',sourceAssetRevision:1,draftHash:'a'.repeat(64),generationIntent:mode,executionPurpose:role==='MAIN_PREVIEW'?null:role,executorType:'COMFY_LOCAL',executorProfile:'OLD',workflowVersion:'old',status,inputSnapshotJson:'{}',outputsJson:JSON.stringify([out]),attemptCount:1,createdAt:time,updatedAt:time});
  await db('o_v04StudioDraftArtifact').insert({artifactId,jobId:id,projectId:scope.projectId,mimeType:'image/png',extension:'png',role,width:32,height:32,createdAt:time});return {id,artifactId,out};
 }
 const main=await source();const mod=loadSource(path.join(root,'src/v04/assetImageEdit.ts'),db,cache,oss);
 const intent={canonicalKey:'CHAR-001',editMode:'TEXT_EDIT',targetRole:'EDIT_CANDIDATE',editPrompt:'Preserve same boy, improve lighting.'};
 return {...f,scope,png,media,main,source,mod,intent};
}
async function settled(f,id,status='SUCCEEDED'){
 const j=await f.db('o_v04StudioAssetDraftJob').where({id}).first(),artifactId=randomUUID();f.media.set(artifactId,f.png);
 await f.db('o_v04StudioDraftArtifact').insert({artifactId,jobId:id,projectId:f.scope.projectId,mimeType:'image/png',extension:'png',role:j.executionPurpose,width:32,height:32,createdAt:Date.now()});await f.db('o_v04StudioAssetDraftJob').where({id}).update({status,outputsJson:JSON.stringify([{artifactId,role:j.executionPurpose}]),updatedAt:Date.now()});return artifactId;
}
test('OPT-029A profiles bind source to both latent patch and grounded encoder; edits cannot silently become T2I',()=>{
 const {buildKreaEditWorkflow:build}=loadSource(path.join(root,'src/v04/kreaImageEditProfile.ts'),null);
 const g=build({profile:'KREA2_REFERENCE_EDIT_V1',prompt:'style only',seed:1,sourceImage:'source.png',referenceImage:'style.png',targetRole:'EDIT_CANDIDATE',jobId:'test'}).graph;
 assert.equal(g['9'].inputs.lora_name,'krea2_identity_edit_v1_2.safetensors');assert.deepEqual(g['12'].inputs.source_latent_b,['8',0]);assert.deepEqual(g['5'].inputs.image_b,['7',0]);assert.deepEqual(g['12'].inputs.target_latent,['4',0]);assert.deepEqual(g['20'].inputs.model,['12',0]);assert.equal(g['12'].inputs.ref_boost,4);assert.equal(g['2'].inputs.device,'cpu');
 assert.throws(()=>build({profile:'KREA2_SOURCE_EDIT_V1',prompt:'edit',seed:1,targetRole:'EDIT_CANDIDATE',jobId:'test'}),e=>e.code==='SOURCE_MISSING');
 assert.throws(()=>build({profile:'KREA2_T2I_ASSET_V1',prompt:'edit',seed:1,sourceImage:'source.png',targetRole:'EDIT_CANDIDATE',jobId:'test'}),e=>e.code==='CAPABILITY_LIMITED');
});
test('OPT-029A enqueue persists frozen lineage but never mutates truth, source job or confirmed specs',async t=>{
 const f=await editFixture(t),before=await f.db('o_v04Asset'),id=randomUUID();const first=await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);const second=await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);assert.equal(first.jobId,second.jobId);const jobs=await f.db('o_v04StudioAssetDraftJob');assert.equal(jobs.length,2);const j=jobs.find(j=>j.id===id),s=JSON.parse(j.inputSnapshotJson);assert.equal(s.sourceArtifactId,f.main.artifactId);assert.equal(s.sourceSha256,pngHash(f.png));assert.equal(j.status,'QUEUED');assert.equal(j.executorProfile,'KREA2_SOURCE_EDIT_V1');assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);assert.equal((await f.db('o_v04AssetPromptBuild')).length,0);assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).first()).status,'SUCCEEDED');
});
test('OPT-029A source role priority and persisted V1 to V2 survive reload, rejected parents cannot be reused',async t=>{
 const f=await editFixture(t);const front=await f.source('FULL_BODY_FRONT','SUCCEEDED',2),face=await f.source('FACE_HERO','SUCCEEDED',3);const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,targetRole:'FACE_HERO'},id);assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).inputSnapshotJson).sourceArtifactId,face.artifactId);await settled(f,id);
 const v2=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,v2,id);const s=JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:v2}).first()).inputSnapshotJson);assert.equal(s.parentCandidateId,id);assert.equal(s.sourceJobId,id);assert.notEqual(s.sourceArtifactId,front.artifactId);assert.equal((await f.mod.listAssetImageCandidates(f.scope)).length,2);await f.mod.rejectAssetImageCandidate({...f.scope,jobId:id});await assert.rejects(f.mod.enqueueAssetImageEdit(f.scope,f.intent,randomUUID(),id),e=>e.code==='PILOT_SOURCE_STALE');
});
test('OPT-029A REAL_REQUIRED / BRAND and cross-unit source are rejected before job insertion',async t=>{
 const f=await editFixture(t);await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({category:'BRAND',assetKind:'BRAND_MARK',sourcePolicy:'REAL_REQUIRED'});await assert.rejects(f.mod.enqueueAssetImageEdit(f.scope,f.intent,randomUUID()),e=>e.code==='PILOT_REAL_REFERENCE_ONLY');assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);await assert.rejects(f.mod.enqueueAssetImageEdit({...f.scope,scriptId:999},f.intent,randomUUID()),e=>e.code==='PILOT_SCOPE_INVALID');
});
test('OPT-029A candidate Preview is zero-write; accept is explicit hash-protected reference promotion and replay-safe',async t=>{
 const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);const artifact=await settled(f,id);const before=await f.db('o_v04Asset');const p=await f.mod.previewAssetImageCandidate({...f.scope,jobId:id});assert.equal((await f.db('o_v04Decision')).length,0);assert.equal((await f.db('o_v04AgentReference')).length,0);
 await assert.rejects(f.mod.acceptAssetImageCandidate({...f.scope,jobId:id,previewHash:'0'.repeat(64)}),e=>e.code==='PILOT_PREVIEW_STALE');const result=await f.mod.acceptAssetImageCandidate({...f.scope,jobId:id,previewHash:p.previewHash});assert.equal(result.artifactId,artifact);assert.equal((await f.db('o_v04AgentReference'))[0].targetType,'ASSET_BIBLE');assert.equal((await f.db('o_v04AgentAttachment'))[0].purpose,'GENERATED_CANDIDATE');await f.mod.acceptAssetImageCandidate({...f.scope,jobId:id,previewHash:p.previewHash});assert.equal((await f.db('o_v04Decision').where({category:'ASSET_IMAGE_EDIT'})).length,1);assert.equal((await f.db('o_v04Decision').where({category:'ASSET_EDIT_BASELINE'})).length,1);assert.equal((await f.db('o_v04AgentAttachment')).length,1);assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);await assert.rejects(f.mod.rejectAssetImageCandidate({...f.scope,jobId:id}),e=>e.code==='PILOT_CANDIDATE_ACCEPTED');
});
test('OPT-029A asset revision drift prevents adoption and reference scope is exact',async t=>{
 const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await settled(f,id);const p=await f.mod.previewAssetImageCandidate({...f.scope,jobId:id});await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({revision:2});await assert.rejects(f.mod.acceptAssetImageCandidate({...f.scope,jobId:id,previewHash:p.previewHash}),e=>e.code==='PILOT_SOURCE_STALE');assert.equal((await f.db('o_v04Decision')).length,0);await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({revision:1});await assert.rejects(f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,referenceBindings:[{attachmentId:randomUUID(),role:'STYLE_REFERENCE'}]},randomUUID()),e=>e.code==='PILOT_REFERENCE_INVALID');
});
test('OPT-029A actual worker uses fake Comfy once, persists artifact; stale completion retains output without becoming current',async t=>{
 const f=await editFixture(t);const http=require('node:http');let prompts=0,hold=false,release;
 const comfy=http.createServer((req,res)=>{res.setHeader('content-type',req.url.startsWith('/view')?'image/png':'application/json');if(req.url==='/upload/image'){req.resume();return res.end(JSON.stringify({name:'source.png',type:'input',subfolder:''}));}if(req.url==='/prompt'){let body='';req.on('data',x=>body+=x);req.on('end',()=>{const g=JSON.parse(body).prompt;assert.equal(g['12'].class_type,'Krea2EditModelPatch');prompts++;res.end(JSON.stringify({prompt_id:'edit-'+prompts}));});return;}if(req.url.startsWith('/history/')){const id=req.url.split('/').pop(),send=()=>res.end(JSON.stringify({[id]:{status:{completed:true},outputs:{'22':{images:[{filename:'edited.png',subfolder:'',type:'output'}]}}}}));if(hold){release=send;}else send();return;}if(req.url.startsWith('/view'))return res.end(f.png);res.statusCode=404;res.end('{}');});await new Promise(r=>comfy.listen(0,'127.0.0.1',r));t.after(()=>comfy.close());await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:'+comfy.address().port,checkpoint:'unused',enabled:1,updatedAt:1});
 const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),true);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).status,'SUCCEEDED');assert.equal(prompts,1);assert.equal((await f.db('o_v04StudioDraftArtifact').where({jobId:id})).length,1);
 // Use a separate scope source, without teaching the fake artifact reader generated files.
 f.media.set(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).outputsJson)[0].artifactId,f.png);const next=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,next);await f.db('o_v04StudioAssetDraftJob').where({id:next}).update({status:'RUNNING'});hold=true;const done=f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id:next}).first(),true);while(!release)await new Promise(r=>setTimeout(r,10));await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({revision:2});release();await done;const stale=await f.db('o_v04StudioAssetDraftJob').where({id:next}).first();assert.equal(stale.status,'STALE');assert.equal(JSON.parse(stale.outputsJson).length,1);assert.equal(prompts,2);assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).first()).status,'SUCCEEDED');
});
test('OPT-029A authenticated Studio HTTP intent persists conversation and candidate; unowned project is blocked',async t=>{
 const f=await editFixture(t),express=require('express'),app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={id:Number(req.headers['x-test-user']||7)};next();});app.use('/api/v04',loadSource(path.join(root,'src/v04/router.ts'),f.db,f.cache,f.oss).default);const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(()=>server.close());
 f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'准备候选',imageIntent:f.intent})];const body={context:{...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}},message:'把这个男孩改得更写实一点，保留睡衣。'};const post=async(route,b,user=7)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/v04'+route,{method:'POST',headers:{'content-type':'application/json','x-test-user':String(user)},body:JSON.stringify(b)});return {status:r.status,data:await r.json()};};
 const r=await post('/agent/studio-turn',body);assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.data.mode,'ASSET_IMAGE_EDIT');assert.equal(r.data.data.applied,false);assert.equal((await f.db('memories').where({role:'user'})).length,1);assert.equal((await f.db('memories').where({role:'assistant'})).length,1);assert.equal((await post('/studio/image-edit/candidates',f.scope)).data.data.length,1);assert.equal((await post('/studio/image-edit/candidates',f.scope,8)).status,403);assert.equal((await f.db('o_v04AgentReference')).length,0);
});
test('OPT-029A failed worker preserves old outputs and never fabricates a successful edit',async t=>{
 const f=await editFixture(t),http=require('node:http');let prompts=0;const server=http.createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/upload/image'){req.resume();res.end(JSON.stringify({name:'source.png',type:'input',subfolder:''}));return;}if(req.url==='/prompt'){prompts++;res.end(JSON.stringify({prompt_id:'fail-prompt'}));return;}if(req.url==='/history/fail-prompt'){res.end(JSON.stringify({'fail-prompt':{status:{status_str:'error',messages:[['execution_error',{exception_message:'CUDA out of memory'}]]}}}));return;}res.end('{}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:'+server.address().port,checkpoint:'unused',enabled:1,updatedAt:1});const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),true);const j=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(j.status,'FAILED');assert.equal(j.errorCode,'OUT_OF_MEMORY');assert.equal(prompts,2);assert.equal(j.attemptCount,2);assert.equal(JSON.parse(j.inputSnapshotJson).recovery.width,512);assert.equal(JSON.parse(j.inputSnapshotJson).recovery.failedPromptId,'fail-prompt');assert.equal(j.outputsJson,'[]');assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).first()).status,'SUCCEEDED');assert.equal((await f.db('o_v04AgentReference')).length,0);
});
test('OPT-029A recovery never resubmits an uncertain in-flight edit',async t=>{
 const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),false);const j=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(j.status,'FAILED');assert.equal(j.errorCode,'EXECUTION_UNCERTAIN');assert.equal(j.comfyPromptId,null);assert.equal((await f.db('o_v04StudioDraftArtifact')).length,1);
});
test('OPT-029A explicit conversational adoption only opens Preview; rejection stays scoped and never applies truth',async t=>{
 const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await settled(f,id);const studio=loadSource(path.join(root,'src/v04/studioTurn.ts'),f.db,f.cache,f.oss);const context={...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}};
 const reply=await studio.answerStudioTurn({context,message:'就用这张',parentCandidateId:id},randomUUID());assert.equal(reply.mode,'ASSET_IMAGE_REVIEW');assert.equal(reply.candidatePreview.jobId,id);assert.equal(reply.applied,false);assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal(f.oss.modelCalls.length,0);const rejected=await studio.answerStudioTurn({context,message:'不要这个版本',parentCandidateId:id},randomUUID());assert.equal(rejected.applied,false);assert.equal((await f.db('o_v04Decision'))[0].status,'REJECTED');assert.equal((await f.db('o_v04AgentReference')).length,0);
});
test('OPT-029A optional real local worker end-to-end stores candidate lineage in disposable SQLite', {skip:process.env.DS_OPT029A_REAL_WORKER!=='1'},async t=>{
 const f=await editFixture(t);const png=fs.readFileSync('D:/comfy/ComfyUI/output/Krea2_turbo_00008_.png');f.media.set(f.main.artifactId,png);await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:8188',checkpoint:'unused',enabled:1,updatedAt:1});const id=randomUUID(),before=await f.db('o_v04Asset');const turn=loadSource(path.join(root,'src/v04/studioTurn.ts'),f.db,f.cache,f.oss);f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'准备候选',imageIntent:{...f.intent,editPrompt:'Keep this same boy, sleepwear, hair, face and bare feet. Refine only realistic fabric and skin texture, full body neutral background.'}})];
 const response=await turn.answerStudioTurn({context:{...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}},message:'把这个男孩改得更写实一点，保留身份和睡衣。'},id);assert.equal(response.imageCandidate.jobId,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),true);const row=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(row.status,'SUCCEEDED',row.errorCode);assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);const artifact=JSON.parse(row.outputsJson)[0],output=path.join(f.oss.testDir,'v04-draft-artifacts',String(f.scope.projectId),artifact.artifactId+'.png');const evidence=path.resolve(__dirname,'../../opt029a-evidence');fs.copyFileSync(output,path.join(evidence,'real-persisted-worker.png'));fs.writeFileSync(path.join(evidence,'real-persisted-worker.json'),JSON.stringify({naturalLanguageInput:'把这个男孩改得更写实一点，保留身份和睡衣。',resolver:'MOCKED_TEXT_PROVIDER',executor:'REAL_LOCAL_COMFY',scope:f.scope,job:row,truthUnchanged:true,confirmedReferenceCount:0},null,2));
});
test('OPT-029A stale projection preserves historical SUCCEEDED row and never offers current adoption',async t=>{const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await settled(f,id);assert.equal((await f.mod.listAssetImageCandidates(f.scope))[0].status,'SUCCEEDED');await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({revision:2});assert.equal((await f.mod.listAssetImageCandidates(f.scope))[0].status,'STALE');assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).status,'SUCCEEDED');});
test('OPT-029A normal HTTP image attachment reaches reference edit; remains conversational until explicit adoption',async t=>{
 const f=await editFixture(t),express=require('express'),app=express();app.use(express.json());app.use((req,_res,next)=>{req.user={id:7};next();});app.use('/api/v04',loadSource(path.join(root,'src/v04/router.ts'),f.db,f.cache,f.oss).default);const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(()=>server.close());const post=async(route,body)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/v04'+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result.data;};const context={...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}};
 const uploaded=await post('/agent/image/upload',{context,name:'style.png',dataUrl:'data:image/png;base64,'+f.png.toString('base64')});f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'参考风格',imageIntent:{...f.intent,editMode:'REFERENCE_EDIT',referenceBindings:[{attachmentId:uploaded.id,role:'STYLE_REFERENCE'}]}})];const response=await post('/agent/studio-turn',{context,message:'参考这张图片的风格修改男孩，保持睡衣。',attachmentIds:[uploaded.id]});const row=await f.db('o_v04StudioAssetDraftJob').where({id:response.imageCandidate.jobId}).first(),snapshot=JSON.parse(row.inputSnapshotJson);assert.equal(row.executorProfile,'KREA2_REFERENCE_EDIT_V1');assert.equal(snapshot.referenceBindings[0].attachmentId,uploaded.id);assert.equal(snapshot.referenceBindings[0].sha256,pngHash(f.png));assert.deepEqual(snapshot.uploadedReferenceIds,[uploaded.id]);assert.equal((await f.db('o_v04AgentAttachment').where({id:uploaded.id}).first()).messageId,response.userMessageId);assert.equal((await f.db('o_v04AgentAttachment').where({id:uploaded.id}).first()).purpose,'CONVERSATIONAL_REFERENCE');assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal(f.oss.visionCalls,1);
});
test('OPT-029A missing source gives a truthful terminal message, not silent T2I or perpetual uncertainty',async t=>{const f=await editFixture(t);await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).update({status:'STALE'});f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'准备',imageIntent:f.intent})];const studio=loadSource(path.join(root,'src/v04/studioTurn.ts'),f.db,f.cache,f.oss);await assert.rejects(studio.answerStudioTurn({context:{...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}},message:'修改男孩图片'},randomUUID()),e=>e.code==='PILOT_SOURCE_MISSING'&&e.terminal===true&&e.checkStatusUseful===false);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);});
async function baselineHttp(t,f){
 const express=require('express'),app=express();app.use(express.json({limit:'12mb'}));app.use((req,_res,next)=>{req.user={id:7};next();});app.use('/api/v04',loadSource(path.join(root,'src/v04/router.ts'),f.db,f.cache,f.oss).default);const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(()=>server.close());
 const post=async(route,body,status=200)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/v04'+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,status,JSON.stringify(result));return status===200?result.data:result;};
 const context={...f.scope,currentStage:'studio',currentRoute:'studio',selectedObject:{type:'ASSET',key:'CHAR-001'}};
 const upload=async(png=f.png)=>post('/agent/image/upload',{context,name:'baseline.png',dataUrl:'data:image/png;base64,'+png.toString('base64')});
 const preview=async(a,role='GENERAL')=>{const turn=await post('/agent/studio-turn',{context,message:role==='FACE_HERO'?'把这张设为脸部参考':role==='FULL_BODY_BACK'?'把这张设为背面参考':'以后以这张作为这个男孩的基准图。',attachmentIds:[a.id]});assert.equal(turn.mode,'ASSET_IMAGE_BASELINE');return turn.baselinePreview;};
 const confirm=p=>post('/studio/image-baseline/confirm',{...f.scope,canonicalKey:p.canonicalKey,attachmentId:p.attachmentId,role:p.role,previewHash:p.previewHash});
 return {post,context,upload,preview,confirm};
}
test('HOTFIX-01 upload/discussion does not bind; explicit baseline uses HTTP Preview/Confirm, replay, pixels and reload',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),before=await f.db('o_v04Asset'),a=await h.upload();assert.equal((await f.db('o_v04Decision')).length,0);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);
 f.oss.studioResponses=[JSON.stringify({mode:'DISCUSS',reply:'仅讨论，不自动修改。'})];await h.post('/agent/studio-turn',{context:h.context,message:'你觉得这张怎么样？',attachmentIds:[a.id]});assert.equal((await f.db('o_v04Decision')).length,0);
 const b=await h.upload(),p=await h.preview(b);assert.equal((await f.db('o_v04Decision')).length,0);assert.equal(p.current.sha256,pngHash(f.png));assert.equal(p.assetName,'Boy');const r=await h.confirm(p);assert.equal(r.applied,true);assert.equal((await h.confirm(p)).replayed,true);assert.equal((await f.db('o_v04Decision').where({category:'ASSET_IMAGE_EDIT'})).length,0);assert.equal((await f.db('o_v04Decision').where({category:'ASSET_EDIT_BASELINE'})).length,1);assert.deepEqual(await f.db('o_v04Asset'),before);
 const old=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,old);await settled(f,old);
 const fresh=loadSource(path.join(root,'src/v04/assetImageEdit.ts'),f.db,new Map([...f.cache].filter(([k])=>!k.endsWith('assetImageEdit.ts')&&!k.endsWith('assetImageBaseline.ts'))),f.oss),id=randomUUID();await fresh.enqueueAssetImageEdit(f.scope,f.intent,id);const snapshot=JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).inputSnapshotJson);assert.equal(snapshot.sourceAttachmentId,b.id);assert.equal(snapshot.sourceSha256,pngHash(f.png));assert.equal(snapshot.sourceJobId,null);assert.equal(snapshot.baselineVersion,r.version);assert.equal((await h.post('/studio/image-baseline/current',f.scope))[0].attachmentId,b.id);
 const v2=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,v2,old);assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:v2}).first()).inputSnapshotJson).parentCandidateId,old);const back=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,useBaseline:true},back,old);assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:back}).first()).inputSnapshotJson).sourceAttachmentId,b.id);
});
test('HOTFIX-01 role bindings coexist; stale confirmations and cross-scope input reject without truth mutation',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f);const a=await h.upload(),p=await h.preview(a);await h.confirm(p);const face=await h.upload(),fp=await h.preview(face,'FACE_HERO');await h.confirm(fp);const back=await h.upload(),bp=await h.preview(back,'FULL_BODY_BACK');await h.confirm(bp);assert.equal((await h.post('/studio/image-baseline/current',f.scope)).length,3);
 for(const [role,expected] of [['FACE_HERO',face.id],['FULL_BODY_BACK',back.id],['EDIT_CANDIDATE',a.id]]){const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,targetRole:role},id);assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).inputSnapshotJson).sourceAttachmentId,expected);}
 const c=await h.upload(),cp=await h.preview(c),d=await h.upload(),dp=await h.preview(d);await h.confirm(cp);await h.post('/studio/image-baseline/confirm',{...f.scope,canonicalKey:dp.canonicalKey,attachmentId:dp.attachmentId,role:dp.role,previewHash:dp.previewHash},409);
 await h.post('/studio/image-baseline/preview',{...f.scope,scriptId:999,canonicalKey:'CHAR-001',attachmentId:a.id},404);await h.post('/studio/image-baseline/preview',{...f.scope,canonicalKey:'CHAR-999',attachmentId:a.id},409);
 await f.db('o_v04Asset').where({projectId:f.scope.projectId}).update({revision:2});await h.post('/studio/image-baseline/confirm',{...f.scope,canonicalKey:p.canonicalKey,attachmentId:p.attachmentId,role:p.role,previewHash:p.previewHash},409);
});
test('HOTFIX-01 uploaded one-off source and external style stay separate; baseline drift retains history',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f);const a=await h.upload(),p=await h.preview(a);await h.confirm(p);const style=await h.upload();f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'仅参考风格',imageIntent:{...f.intent,referenceBindings:[{attachmentId:style.id,role:'STYLE_REFERENCE'}]}})];const turn=await h.post('/agent/studio-turn',{context:h.context,message:'只参考这张图的风格和光影',attachmentIds:[style.id]});const s=JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:turn.imageCandidate.jobId}).first()).inputSnapshotJson);assert.equal(s.sourceAttachmentId,a.id);assert.equal(s.referenceBindings[0].attachmentId,style.id);await settled(f,turn.imageCandidate.jobId);
 const one=await h.upload();f.oss.studioResponses=[JSON.stringify({mode:'ASSET_IMAGE_EDIT',reply:'本次改图',imageIntent:{...f.intent,sourceAttachmentId:one.id}})];const once=await h.post('/agent/studio-turn',{context:h.context,message:'用这张试着改得更写实',attachmentIds:[one.id]});assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:once.imageCandidate.jobId}).first()).inputSnapshotJson).sourceAttachmentId,one.id);assert.equal((await h.post('/studio/image-baseline/current',f.scope))[0].attachmentId,a.id);
 const newer=await h.upload(),np=await h.preview(newer);await h.confirm(np);const historical=await f.db('o_v04StudioAssetDraftJob').where({id:turn.imageCandidate.jobId}).first();assert.equal(historical.status,'SUCCEEDED');assert.equal((await f.mod.listAssetImageCandidates(f.scope)).find(j=>j.id===historical.id).status,'STALE');assert.ok(JSON.parse(historical.outputsJson).length);
});
test('HOTFIX-01 baseline operation is available without optional vision or text model',async t=>{const f=await editFixture(t),h=await baselineHttp(t,f);f.oss.textModelUnavailable=true;f.oss.visionModel=null;const a=await h.upload(),p=await h.preview(a);assert.equal(f.oss.modelCalls.length,0);assert.equal(f.oss.visionCalls,0);await h.confirm(p);});
test('HOTFIX-01 real uploaded baseline HTTP and local Comfy worker, plus explicit V2 lineage', {skip:process.env.DS_OPT029AH1_REAL!=='1'},async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),png=fs.readFileSync('D:/comfy/ComfyUI/output/Krea2_turbo_00008_.png'),a=await h.upload(png),p=await h.preview(a);await h.confirm(p);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);
 await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:8188',checkpoint:'unused',enabled:1,updatedAt:1});const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,editPrompt:'Keep the same boy, face, short dark hair, pale gray sleepwear and bare feet. Refine only realistic fabric texture. Full body neutral background.'},id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});const started=Date.now();await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),true);const job=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(job.status,'SUCCEEDED',job.errorCode);const snapshot=JSON.parse(job.inputSnapshotJson);assert.equal(snapshot.sourceAttachmentId,a.id);assert.equal(snapshot.sourceSha256,pngHash(png));const output=JSON.parse(job.outputsJson)[0];
 const file=path.join(f.oss.testDir,'v04-draft-artifacts',String(f.scope.projectId),output.artifactId+'.png'),evidence=path.resolve(__dirname,'../../opt029ah1-evidence');fs.mkdirSync(evidence,{recursive:true});const bytes=fs.readFileSync(file);fs.copyFileSync(file,path.join(evidence,'uploaded-baseline-edit.png'));f.media.set(output.artifactId,bytes);const child=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,child,id);assert.equal(JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id:child}).first()).inputSnapshotJson).parentCandidateId,id);
 fs.writeFileSync(path.join(evidence,'real-worker.json'),JSON.stringify({resolver:'MOCKED_TEXT_PROVIDER; real router upload/preview/confirm + real executor',seconds:(Date.now()-started)/1000,upload:a,baseline:p,job,parentChild:{parent:id,child},protectedTruth:{assets:await f.db('o_v04Asset'),visualSpecs:await f.db('o_v04AssetVisualSpec')}},null,2));
});
test('HOTFIX-01 concurrent confirm is idempotent; late output is retained and unrelated role stays current',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),a=await h.upload(),p=await h.preview(a);const results=await Promise.all([h.confirm(p),h.confirm(p)]);assert.equal(results[0].version,results[1].version);assert.equal((await f.db('o_v04Decision').where({category:'ASSET_EDIT_BASELINE'})).length,1);
 const face=await h.upload(),fp=await h.preview(face,'FACE_HERO');await h.confirm(fp);const faceJob=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,targetRole:'FACE_HERO'},faceJob);await settled(f,faceJob);
 const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING',comfyPromptId:null});const newer=await h.upload(),np=await h.preview(newer);await h.confirm(np);assert.equal((await f.mod.listAssetImageCandidates(f.scope)).find(j=>j.id===faceJob).status,'SUCCEEDED');
 // Admission already froze A. Recheck must settle stale, never change its source
 // or discard a terminal image; producer's existing late-output test covers IO.
 const snapshot=JSON.parse((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).inputSnapshotJson);assert.equal(snapshot.sourceAttachmentId,a.id);await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),false);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id}).first()).status,'STALE');assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).first()).status,'SUCCEEDED');
});
test('HOTFIX-01 recovered submitted job keeps late output after baseline switch, with no resubmission',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),a=await h.upload(),p=await h.preview(a);await h.confirm(p);const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING',comfyPromptId:'already-submitted'});
 const newer=await h.upload(),np=await h.preview(newer);await h.confirm(np);const http=require('node:http');let submits=0,history=0;const server=http.createServer((req,res)=>{if(req.url==='/prompt'){submits++;res.statusCode=500;return res.end('{}');}if(req.url==='/history/already-submitted'){history++;res.setHeader('content-type','application/json');return res.end(JSON.stringify({'already-submitted':{status:{completed:true},outputs:{'22':{images:[{filename:'late.png',subfolder:'',type:'output'}]}}}}));}if(req.url.startsWith('/view')){res.setHeader('content-type','image/png');return res.end(f.png);}res.statusCode=404;res.end('{}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());let job=await f.db('o_v04StudioAssetDraftJob').where({id}).first();const snapshot=JSON.parse(job.inputSnapshotJson);snapshot.baseUrl='http://127.0.0.1:'+server.address().port;await f.db('o_v04StudioAssetDraftJob').where({id}).update({inputSnapshotJson:JSON.stringify(snapshot)});job=await f.db('o_v04StudioAssetDraftJob').where({id}).first();await f.mod.produceAssetImageEdit(job,false);const final=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(final.status,'STALE');assert.equal(submits,0);assert.equal(history,1);assert.equal(JSON.parse(final.outputsJson).length,1);assert.equal(JSON.parse(final.inputSnapshotJson).sourceAttachmentId,a.id);assert.equal((await h.post('/studio/image-baseline/current',f.scope))[0].attachmentId,newer.id);
});
test('HOTFIX-01 attachment-only message needs no model and has zero baseline/job writes',async t=>{const f=await editFixture(t),h=await baselineHttp(t,f),a=await h.upload();f.oss.textModelUnavailable=true;const result=await h.post('/agent/studio-turn',{context:h.context,message:'[图片参考]',attachmentIds:[a.id]});assert.equal(result.mode,'DISCUSS');assert.equal(f.oss.modelCalls.length,0);assert.equal((await f.db('o_v04Decision')).length,0);assert.equal((await f.db('o_v04AgentReference')).length,0);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);});

test('OPT-029C routing HTTP preview is zero-write; compatible apply/replay/reset and disabled admissions',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),projectId=f.scope.projectId;
 const request={projectId,requestId:randomUUID(),routes:{SOURCE_EDIT:'KREA2_T2I_ASSET_V1'}};
 await h.post('/operations/routing/preview',request,409);assert.equal((await f.db('o_v04RoutingChange')).length,0);
 const p=await h.post('/operations/routing/preview',{projectId,requestId:randomUUID(),disabledProfiles:['KREA2_SOURCE_EDIT_V1']});assert.equal((await f.db('o_v04RoutingChange')).length,0);
 const body={...p.request,previewHash:p.previewHash,confirmed:true};const result=await h.post('/operations/routing/apply',body);assert.equal(result.version,1);assert.equal((await h.post('/operations/routing/apply',body)).replayed,true);
 await assert.rejects(f.mod.enqueueAssetImageEdit(f.scope,f.intent,randomUUID()),e=>e.code==='PILOT_IMAGE_ROUTING_DISABLED');assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,1);
 const reset=await h.post('/operations/routing/preview',{projectId,requestId:randomUUID(),reset:true});await h.post('/operations/routing/apply',{...reset.request,previewHash:reset.previewHash,confirmed:true});await f.mod.enqueueAssetImageEdit(f.scope,f.intent,randomUUID());
 const changes=await f.db('o_v04RoutingChange');assert.equal(changes.length,2);assert.equal(changes[0].actorUserId,7);
 await h.post('/operations/routing/preview',{projectId:999,requestId:randomUUID()},403);
});
test('OPT-029C exact graph committed before HTTP submit; scoped bounded summaries, safe graph, status and output persistence',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),client=loadSource(path.join(root,'src/v04/tracedDraftSubmit.ts'),f.db,f.cache,f.oss),trace=loadSource(path.join(root,'src/v04/executionTrace.ts'),f.db,f.cache,f.oss),registry=loadSource(path.join(root,'src/v04/operationsRegistry.ts'),f.db,f.cache,f.oss);
 const id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);const job=await f.db('o_v04StudioAssetDraftJob').where({id}).first();const wf=registry.profileExample('KREA2_SOURCE_EDIT_V1');let submitted;
 const server=require('node:http').createServer((req,res)=>{let body='';req.on('data',x=>body+=x);req.on('end',async()=>{submitted=JSON.parse(body).prompt;const row=await f.db('o_v04ExecutionTrace').where({jobId:id}).first();assert.ok(row);assert.deepEqual(JSON.parse(row.workflowGraphJson),submitted);assert.equal(row.workflowGraphHash,pngHash(Buffer.from(JSON.stringify(submitted))));res.setHeader('content-type','application/json');res.end(JSON.stringify({prompt_id:'exact-prompt'}));});});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());
 await client.submitTracedDraft('http://127.0.0.1:'+server.address().port,wf,job);
 const row=await f.db('o_v04ExecutionTrace').where({jobId:id}).first();assert.equal(row.status,'RUNNING');assert.equal(row.comfyPromptId,'exact-prompt');
 const list=await h.post('/operations/executions',{projectId:f.scope.projectId});assert.equal(list.length,1);assert.equal(list[0].workflowGraphJson,undefined);
 const detail=await h.post('/operations/execution',{projectId:f.scope.projectId,traceId:row.id});assert.equal(detail.workflowGraphHash,pngHash(Buffer.from(detail.workflowGraphJson)));assert.equal(JSON.parse(detail.workflowGraphJson)['22'].class_type,'SaveImage');
 const second=await f.service.createPilotProject({name:'Other',brief:'Other',targetDuration:30,aspectRatio:'16:9'},7);await h.post('/operations/execution',{projectId:second.projectId,traceId:row.id},404);
 for(const status of ['SUCCEEDED','STALE']){await f.db('o_v04StudioAssetDraftJob').where({id}).update({status,outputsJson:JSON.stringify([{artifactId:f.main.artifactId}]),completedAt:5});if(status==='STALE')await f.db('o_v04ExecutionTrace').where({id:row.id}).update({status:'RUNNING'});await trace.settleJobTraces(id);assert.equal((await f.db('o_v04ExecutionTrace').where({id:row.id}).first()).status,status);}
 await trace.failTrace(row.id,'OUT_OF_MEMORY');assert.equal((await h.post('/operations/executions',{projectId:f.scope.projectId,filter:'Failed'}))[0].errorCode,'OUT_OF_MEMORY');
 for(const key of ['api_key','password','authorization','cookie','headers'])assert.throws(()=>trace.assertTraceSafe({inputs:{[key]:'secret'}}));
 assert.throws(()=>trace.assertTraceSafe({url:'http://a:b@localhost/'}));assert.throws(()=>trace.assertTraceSafe({image:'data:image/png;base64,abc'}));
 const unsafe={...wf,graph:{'1':{class_type:'Unsafe',inputs:{api_key:'do-not-send'}}}};await assert.rejects(client.submitTracedDraft('http://127.0.0.1:'+server.address().port,unsafe,job),/SENSITIVE/);assert.equal((await f.db('o_v04ExecutionTrace')).length,1);
 assert.ok(registry.workflowRegistry().every(p=>p.sourceType==='CODE_GENERATED'&&p.jsonFile===null));assert.equal(registry.workflowRegistry().find(p=>p.profile==='KREA2_T2I_ASSET_V1').wiring,'AUTO_ASSET');
});
test('OPT-029C health reads actual object_info; missing node and model are distinct and no submit occurs',async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f);let submits=0;const server=require('node:http').createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/prompt')submits++;res.end(JSON.stringify(req.url==='/system_stats'?{system:{comfyui_version:'test'},devices:[{name:'test GPU',vram_total:123,vram_free:12}]}:req.url==='/queue'?{queue_running:[],queue_pending:[]} : {}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:'+server.address().port,checkpoint:'missing',enabled:1,updatedAt:1});
 const state=await h.post('/operations/status',{projectId:f.scope.projectId});assert.equal(state.comfy.version,'test');assert.equal(state.comfy.devices[0].vram_total,123);const krea=state.registry.find(p=>p.profile==='KREA2_SOURCE_EDIT_V1');assert.ok(krea.missingNodes.includes('Krea2EditGroundedEncode'));assert.ok(krea.missingModels.includes('krea2_turbo_fp8_scaled.safetensors'));assert.equal(submits,0);
});
test('OPT-029C real Krea edit has Professional detail/export exact trace', {skip:process.env.DS_OPT029C_REAL!=='1'},async t=>{
 const f=await editFixture(t),h=await baselineHttp(t,f),png=fs.readFileSync('D:/comfy/ComfyUI/output/Krea2_turbo_00008_.png'),a=await h.upload(png),p=await h.preview(a);await h.confirm(p);
 await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:8188',checkpoint:'unused',enabled:1,updatedAt:1});const before=await f.db('o_v04Asset'),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,{...f.intent,editPrompt:'Preserve this same boy, face, hair, gray sleepwear and bare feet. Only soften the studio lighting. Full body.'},id);await f.db('o_v04StudioAssetDraftJob').where({id}).update({status:'RUNNING'});const started=Date.now();await f.mod.produceAssetImageEdit(await f.db('o_v04StudioAssetDraftJob').where({id}).first(),true);const job=await f.db('o_v04StudioAssetDraftJob').where({id}).first();assert.equal(job.status,'SUCCEEDED',job.errorCode);assert.deepEqual(await f.db('o_v04Asset'),before);
 const list=await h.post('/operations/executions',{projectId:f.scope.projectId}),d=await h.post('/operations/execution',{projectId:f.scope.projectId,traceId:list[0].id});assert.equal(d.status,'SUCCEEDED');assert.equal(d.comfyPromptId,job.comfyPromptId);assert.equal(d.workflowGraphHash,pngHash(Buffer.from(d.workflowGraphJson)));assert.equal(JSON.parse(d.workflowGraphJson)['22'].class_type,'SaveImage');assert.equal(JSON.parse(d.parametersJson).steps,8);assert.equal(JSON.parse(d.modelsJson).length,4);
 const out=JSON.parse(job.outputsJson)[0],dir=path.resolve(__dirname,'../../opt029c-evidence');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'actual-comfy-graph.json'),d.workflowGraphJson);fs.copyFileSync(path.join(f.oss.testDir,'v04-draft-artifacts',String(f.scope.projectId),out.artifactId+'.png'),path.join(dir,'boy-edit.png'));fs.writeFileSync(path.join(dir,'real-execution.json'),JSON.stringify({seconds:(Date.now()-started)/1000,job,trace:d,professionalApiVerified:true,scope:f.scope,auth:'isolated HTTP harness authenticated actor; not live browser login',truthUnchanged:true},null,2));
});

test('OPT-029B reconciler admits first drafts before independent packs, dedupes, preserves authority and rejects real assets',async t=>{
 const f=await editFixture(t),auto=loadSource(path.join(root,'src/v04/autoAsset.ts'),f.db,f.cache,f.oss),contract=loadSource(path.join(root,'src/v04/visualSpecContract.ts'),f.db,f.cache,f.oss);
 const original=await f.db('o_v04Asset').first();
 const specFor=a=>contract.compileVisualSemantic({...a,identityAnchors:[],mustPreserve:[],forbiddenChanges:[]},{visualIdentitySummary:a.name});
 const assets=[['CHAR-002','CREATURE','CHAR'],['PROP-001','VEHICLE','PROP'],['LOC-001','ENVIRONMENT','LOC'],['FX-001','MATERIAL_FX','FX']];
 for(const [canonicalKey,assetKind,category] of assets)await f.db('o_v04Asset').insert({...original,canonicalKey,assetKind,category,name:canonicalKey});
 await f.db('o_v04Asset').insert({...original,canonicalKey:'BRAND-001',category:'BRAND',assetKind:'BRAND_MARK',sourcePolicy:'REAL_REQUIRED'});
 const all=await f.db('o_v04Asset'),items=all.filter(a=>a.sourcePolicy==='AI_ALLOWED').map(a=>({canonicalKey:a.canonicalKey,sourceAssetRevision:1,spec:specFor(a)}));
 const before=await f.db('o_v04Asset');await auto.reconcileAutoAssets({...f.scope,items});
 const first=await f.db('o_v04StudioAssetDraftJob').where({executionPurpose:'ASSET_MAIN_PREVIEW'});assert.equal(first.length,4);assert.ok(first.every(j=>j.executorProfile==='KREA2_T2I_ASSET_V1'));
 assert.equal((await f.db('o_v04StudioAssetDraftJob').where({canonicalKey:'BRAND-001'})).length,0);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({canonicalKey:'CHAR-001'})).length,1);
 assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);
 await Promise.all([auto.reconcileAutoAssets({...f.scope,items}),auto.reconcileAutoAssets({...f.scope,items})]);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,5);
 // No pack before first coverage is settled; a failed first draft is not silently retried.
 await f.db('o_v04StudioAssetDraftJob').where({executionPurpose:'ASSET_MAIN_PREVIEW'}).update({status:'FAILED'});
 const directory=path.join(f.oss.testDir,'v04-draft-artifacts',String(f.scope.projectId));fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(path.join(directory,f.main.artifactId+'.png'),f.png);
 await auto.reconcileAutoAssets({...f.scope,items});const packs=await f.db('o_v04StudioAssetDraftJob').whereNotNull('executionPurpose').whereNot({executionPurpose:'ASSET_MAIN_PREVIEW'});assert.equal(packs.length,3);
 assert.deepEqual(packs.map(j=>j.executionPurpose).sort(),['FACE_HERO','FULL_BODY_BACK','FULL_BODY_FRONT']);assert.ok(packs.every(j=>JSON.parse(j.inputSnapshotJson).sourceArtifactId===f.main.artifactId));
 const p=packs[0];assert.equal(await auto.autoJobFresh(p),true);await f.db('o_v04Asset').where({canonicalKey:'CHAR-001'}).update({revision:2});assert.equal(await auto.autoJobFresh(p),false);
 for(const key of ['CHAR-002','PROP-001']){const main=first.find(j=>j.canonicalKey===key),artifactId=randomUUID();await f.db('o_v04StudioDraftArtifact').insert({artifactId,jobId:main.id,projectId:f.scope.projectId,mimeType:'image/png',extension:'png',role:'MAIN_PREVIEW',width:32,height:32,createdAt:2});fs.writeFileSync(path.join(directory,artifactId+'.png'),f.png);await f.db('o_v04StudioAssetDraftJob').where({id:main.id}).update({status:'SUCCEEDED',outputsJson:JSON.stringify([{artifactId,role:'MAIN_PREVIEW'}])});}
 await auto.reconcileAutoAssets({...f.scope,items});for(const [key,count] of [['CHAR-002',3],['PROP-001',4]]){const rows=await f.db('o_v04StudioAssetDraftJob').where({canonicalKey:key}).whereNot({executionPurpose:'ASSET_MAIN_PREVIEW'});assert.equal(rows.length,count);assert.equal(new Set(rows.map(j=>JSON.parse(j.inputSnapshotJson).sourceArtifactId)).size,1);assert.ok(rows.every(j=>j.executorProfile==='KREA2_DERIVE_ASSET_REFERENCE_V1'));}
 const registry=loadSource(path.join(root,'src/v04/operationsRegistry.ts'),f.db,f.cache,f.oss);assert.equal(registry.workflowRegistry().find(p=>p.profile==='KREA2_T2I_ASSET_V1').wiring,'AUTO_ASSET');
});

test('OPT-029B disabled routing admits zero jobs and offline pauses without submitting',async t=>{
 const f=await editFixture(t),auto=loadSource(path.join(root,'src/v04/autoAsset.ts'),f.db,f.cache,f.oss),contract=loadSource(path.join(root,'src/v04/visualSpecContract.ts'),f.db,f.cache,f.oss);
 await f.db('o_v04StudioAssetDraftJob').delete();const a=await f.db('o_v04Asset').first(),spec=contract.compileVisualSemantic({...a,identityAnchors:[],mustPreserve:[],forbiddenChanges:[]},{visualIdentitySummary:'Boy'}),input={...f.scope,items:[{canonicalKey:a.canonicalKey,sourceAssetRevision:1,spec}]};
 const ops=loadSource(path.join(root,'src/v04/operations.ts'),f.db,f.cache,f.oss),req={projectId:f.scope.projectId,requestId:randomUUID(),disabledProfiles:['KREA2_T2I_ASSET_V1']};const preview=await ops.previewRouting(req);await ops.applyRouting({...req,previewHash:preview.previewHash,confirmed:true},7);
 await auto.reconcileAutoAssets(input);assert.equal((await f.db('o_v04StudioAssetDraftJob')).length,0);
 await f.db('o_v04RoutingChange').delete();await auto.reconcileAutoAssets(input);const j=await f.db('o_v04StudioAssetDraftJob').first();
 const http=require('node:http');let prompts=0;const server=http.createServer((req,res)=>{if(req.url==='/prompt')prompts++;res.statusCode=503;res.end();});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const snap=JSON.parse(j.inputSnapshotJson);snap.baseUrl='http://127.0.0.1:'+server.address().port;j.inputSnapshotJson=JSON.stringify(snap);await f.db('o_v04StudioAssetDraftJob').where({id:j.id}).update({status:'RUNNING',inputSnapshotJson:j.inputSnapshotJson});
 assert.deepEqual(await auto.produceAutoAsset(j,true),{paused:true});assert.equal(prompts,0);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:j.id}).first()).status,'QUEUED');assert.equal((await f.db('o_v04ExecutionTrace')).length,0);
});

test('OPT-029B role plans and composition are kind-specific and bounded',()=>{
 const m=loadSource(path.join(root,'src/v04/autoAssetPrompt.ts'),null);for(const [kind,n] of [['HUMAN_CHARACTER',3],['CREATURE',3],['VEHICLE',4],['PROP',3],['ENVIRONMENT',0],['MATERIAL_FX',0],['CELESTIAL',0]]){assert.equal(m.autoAssetRoles({assetKind:kind,importance:'CORE',sourcePolicy:'AI_ALLOWED'}).length,n);assert.deepEqual(m.autoAssetRoles({assetKind:kind,importance:'SUPPORTING',sourcePolicy:'AI_ALLOWED'}),[]);const r=m.autoAssetResolution(kind);assert.equal(r.width%64,0);assert.equal(r.height%64,0);assert.ok(r.width*r.height>=600000&&r.width*r.height<=1000000);}
});

 test('OPT-029B live worker lease is exclusive across processes and released without time-based stealing',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'v04-worker-lease-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'worker.lock');
 const lease=loadSource(path.join(root,'src/v04/draftWorkerLease.ts'),null),release=await lease.acquireDraftWorkerLease(file);assert.equal(typeof release,'function');assert.equal(await lease.acquireDraftWorkerLease(file),null);
 const cp=require('node:child_process'),script=path.join(dir,'child.cjs');fs.writeFileSync(script,`const fs=require('fs'),ts=require(${JSON.stringify(require.resolve('typescript'))});const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(${JSON.stringify(path.join(root,'src/v04/draftWorkerLease.ts'))},'utf8'),{compilerOptions:{module:1,target:9,esModuleInterop:true}}).outputText)(require,m,m.exports);m.exports.acquireDraftWorkerLease(${JSON.stringify(file)}).then(x=>{console.log(x?'ACQUIRED':'BLOCKED');if(x)return x()});`);
 const result=cp.spawnSync(process.execPath,[script],{encoding:'utf8'});assert.equal(result.status,0);assert.match(result.stdout,/BLOCKED/);await release();const next=await lease.acquireDraftWorkerLease(file);assert.equal(typeof next,'function');await next();assert.equal(fs.existsSync(file),false);
 });

test('OPT-029B real worker with fake Comfy traces exact T2I graph and preserves truth on success and bounded OOM',async t=>{
 const f=await editFixture(t),auto=loadSource(path.join(root,'src/v04/autoAsset.ts'),f.db,f.cache,f.oss),contract=loadSource(path.join(root,'src/v04/visualSpecContract.ts'),f.db,f.cache,f.oss);
 await f.db('o_v04StudioAssetDraftJob').delete();let prompts=0,oom=false;const http=require('node:http'),graphs=[];
 const server=http.createServer((req,res)=>{if(req.url==='/system_stats'){res.end('{}');return;}if(req.url==='/prompt'){let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{graphs.push(JSON.parse(raw).prompt);res.end(JSON.stringify({prompt_id:'auto-'+(++prompts)}));});return;}if(req.url.startsWith('/history/')){const id=req.url.split('/').pop();res.end(JSON.stringify({[id]:oom?{status:{status_str:'error',messages:[['execution_error',{exception_message:'CUDA out of memory'}]]}}:{status:{status_str:'success',completed:true},outputs:{22:{images:[{filename:'auto.png',type:'output',subfolder:''}]}}}}));return;}if(req.url.startsWith('/view')){res.setHeader('content-type','image/png');res.end(f.png);return;}res.end('{}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());
 await f.db('o_v04StudioImageExecutorConfig').insert({projectId:f.scope.projectId,baseUrl:'http://127.0.0.1:'+server.address().port,checkpoint:'unused',enabled:1,updatedAt:1});
 const asset=await f.db('o_v04Asset').first(),spec=contract.compileVisualSemantic({...asset,identityAnchors:[],mustPreserve:[],forbiddenChanges:[]},{visualIdentitySummary:'Boy'});const input={...f.scope,items:[{canonicalKey:asset.canonicalKey,sourceAssetRevision:1,spec}]};
 const before=await f.db('o_v04Asset');await auto.reconcileAutoAssets(input);let job=await f.db('o_v04StudioAssetDraftJob').first();await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).update({status:'RUNNING'});await auto.produceAutoAsset(job,true);
 let result=await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).first();assert.equal(result.status,'SUCCEEDED');assert.equal(JSON.parse(result.outputsJson)[0].role,'MAIN_PREVIEW');const trace=await f.db('o_v04ExecutionTrace').where({jobId:job.id}).first();assert.equal(trace.status,'SUCCEEDED');assert.deepEqual(JSON.parse(trace.workflowGraphJson),graphs[0]);assert.equal(graphs[0]['5'].class_type,'CLIPTextEncode');assert.equal(Object.values(graphs[0]).some(n=>n.class_type==='LoadImage'),false);
 assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);assert.equal((await f.db('o_v04AgentReference')).length,0);
 const choices=await f.mod.listAssetImageCandidates(f.scope);assert.equal(choices.find(c=>c.id===job.id).automatic,true);const review=await f.mod.previewAssetImageCandidate({...f.scope,jobId:job.id});assert.equal((await f.db('o_v04Decision')).length,0);f.media.set(JSON.parse(result.outputsJson)[0].artifactId,f.png);await f.mod.acceptAssetImageCandidate({...f.scope,jobId:job.id,previewHash:review.previewHash});assert.equal((await f.db('o_v04Decision').where({category:'ASSET_EDIT_BASELINE'})).length,1);assert.equal((await f.db('o_v04AssetVisualSpec')).length,0);
 oom=true;await auto.reconcileAutoAssets({...input,regenerateKey:asset.canonicalKey,requestId:randomUUID()});job=await f.db('o_v04StudioAssetDraftJob').whereNot({id:job.id}).first();await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).update({status:'RUNNING'});await auto.produceAutoAsset(job,true);result=await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).first();assert.equal(result.status,'QUEUED');assert.equal(result.attemptCount,2);assert.equal(JSON.parse(result.inputSnapshotJson).width,512);
 await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).update({status:'RUNNING'});await auto.produceAutoAsset(result,true);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({id:job.id}).first()).status,'FAILED');assert.equal(prompts,3);assert.deepEqual(await f.db('o_v04Asset'),before);assert.equal((await f.db('o_v04StudioAssetDraftJob').where({status:'SUCCEEDED'})).length,1);
});

 test('02A public draft and edit candidate DTO preserve persisted timing including legacy null',async t=>{
 const f=await editFixture(t),id=randomUUID();await f.mod.enqueueAssetImageEdit(f.scope,f.intent,id);
 let c=(await f.mod.listAssetImageCandidates(f.scope)).find(j=>j.id===id);assert.equal(c.startedAt,null);assert.equal(c.completedAt,null);assert.equal(c.generationIntent,'ASSET_IMAGE_EDIT');assert.equal(c.automatic,false);
 await f.db('o_v04StudioAssetDraftJob').where({id}).update({startedAt:1234,completedAt:5678,updatedAt:5678});c=(await f.mod.listAssetImageCandidates(f.scope)).find(j=>j.id===id);assert.equal(c.startedAt,1234);assert.equal(c.completedAt,5678);assert.equal(c.updatedAt,5678);
 const cache=new Map(f.cache);cache.delete(path.join(root,'src/v04/studioDraftImage.ts'));const drafts=loadSource(path.join(root,'src/v04/studioDraftImage.ts'),f.db,cache,f.oss);
 let main=(await drafts.listDraftJobs(f.scope)).find(j=>j.id===f.main.id);assert.equal(main.startedAt,null);assert.equal(main.completedAt,null);
 await f.db('o_v04StudioAssetDraftJob').where({id:f.main.id}).update({startedAt:2000,completedAt:8000});main=(await drafts.listDraftJobs(f.scope)).find(j=>j.id===f.main.id);assert.equal(main.startedAt,2000);assert.equal(main.completedAt,8000);
 });
