import fs from 'node:fs/promises';import path from 'node:path';import {buildKreaEditWorkflow,uploadEditInput} from '../src/v04/kreaImageEditProfile';import {submitDraft,awaitDraft,downloadDraft} from '../src/v04/comfyDraftClient';
void(async()=>{const dir=path.resolve('../opt029a-evidence'),base='http://127.0.0.1:8188',source='D:/comfy/ComfyUI/output/Krea2_turbo_00008_.png',reference='D:/comfy/ComfyUI/output/Krea2_turbo_00013_.png';const src=await uploadEditInput(base,await fs.readFile(source),'ds-opt029a-good-front.png'),ref=await uploadEditInput(base,await fs.readFile(reference),'ds-opt029a-wuxia-style.png');const results:any[]=[];
async function run(name:string,prompt:string,profile:string,sourceImage?:string,referenceImage?:string,role='EDIT_CANDIDATE'){const wf=buildKreaEditWorkflow({profile,prompt,seed:29010+results.length,width:768,height:768,sourceImage,referenceImage,targetRole:role,jobId:'029a-'+name});await fs.writeFile(path.join(dir,name+'-workflow.json'),JSON.stringify(wf,null,2));const start=Date.now(),id=await submitDraft(base,wf);console.log('SUBMITTED',name,id);try{const image=await awaitDraft(base,id,wf.outputNode,1200000),output=await downloadDraft(base,image),out=path.join(dir,name+'.png');await fs.writeFile(out,output.bytes);const r={name,id,prompt,seconds:(Date.now()-start)/1000,out,width:output.width,height:output.height,sourceImage,referenceImage,profile,role,status:'SUCCEEDED',oom:false};results.push(r);await fs.writeFile(path.join(dir,'real-results.json'),JSON.stringify({source,reference,results},null,2));console.log(JSON.stringify(r));return out;}catch(e:any){results.push({name,id,status:'FAILED',code:e.code,seconds:(Date.now()-start)/1000});await fs.writeFile(path.join(dir,'real-results.json'),JSON.stringify({source,reference,results},null,2));console.error(name,e);return null;}}
const edited=await run('good-front-text-edit','Edit this same young boy into refined cinematic stylized realism, natural child proportions, subtle realistic skin and fabric. Preserve the same face, age, messy short dark hair, slim body, loose pale grey sleep shirt and grey pants, barefoot. Full body neutral background. No new accessories.','KREA2_SOURCE_EDIT_V1',src);
await run('good-front-reference-edit','Image 1 supplies only cinematic wuxia 3D rendering and moody lighting. Image 2 supplies the boy identity and clothes. Preserve child age, face, messy short dark hair, slim body, pale grey sleep shirt and grey trousers, barefoot. Single boy full body neutral background. Do not copy the adult, hairstyle, costume or architecture from image 1.','KREA2_REFERENCE_EDIT_V1',src,ref);
await run('good-front-face-hero','Create a chest-up portrait of this exact same boy directly facing camera. Preserve facial identity, child age, short messy dark hair, pale grey sleep shirt and cinematic stylized realism. Neutral background. Do not redesign.','KREA2_DERIVE_CHARACTER_REFERENCE_V1',src,undefined,'FACE_HERO');
await run('good-front-full-body-back','Create a full-body rear view of this same boy, camera directly behind, face not visible. Preserve short messy dark hair silhouette, slim child proportions, pale grey loose sleep shirt, grey trousers, barefoot, cinematic stylized realism. Neutral background. No accessories.','KREA2_DERIVE_CHARACTER_REFERENCE_V1',src,undefined,'FULL_BODY_BACK');
if(edited){const v1=await uploadEditInput(base,await fs.readFile(edited),'ds-opt029a-v1-source.png');await run('candidate-v2','Edit the same boy from this source version, keeping lighting, sleepwear, body, hair and face. Make only the eyes less oversized and more anatomically natural. Keep child age, barefoot and full body.','KREA2_SOURCE_EDIT_V1',v1);}
const ship=await run('ship-disposable-source','One old wooden pirate sailing ship with three tall masts, pale weathered sails and dark timber hull. Detailed cinematic concept art, whole ship visible on calm water under cloudy sky.','KREA2_T2I_ASSET_V1');if(ship){const s=await uploadEditInput(base,await fs.readFile(ship),'ds-opt029a-ship-source.png');await run('ship-text-edit','Edit this same pirate ship, preserve main hull silhouette and mast layout. Make timber darker and more weathered, sails worn, mood somber, cinematic concept art. Keep complete ship visible, no new masts or ornaments.','KREA2_SOURCE_EDIT_V1',s);}
})().catch(e=>{console.error(e);process.exitCode=1});
