import {createHash,randomUUID} from 'node:crypto';
import type {Knex} from 'knex';
import sharp from 'sharp';
import {z} from 'zod';
import {db} from '@/utils/db';
import {getAgentAttachmentBytes} from './agentAttachments';
import {PilotError} from './service';
const q=db as Knex;
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const baselineRequest=z.object({projectId:z.number().int().positive(),scriptId:z.number().int().positive(),canonicalKey:z.string().min(1).max(128),attachmentId:z.string().uuid(),role:z.enum(['GENERAL','FACE_HERO','FULL_BODY_FRONT','FULL_BODY_BACK','DETAIL_REFERENCE']).default('GENERAL')}).strict();
const scopeSchema=baselineRequest.pick({projectId:true,scriptId:true});
// An accepted Decision is the binding/version. This does not pretend an upload
// was generated by Comfy and does not replace an existing production image.
export async function baselinesInTransaction(trx:Knex.Transaction,scope:{projectId:number;scriptId:number}){
 const records=await trx('o_v04Decision').where({projectId:scope.projectId,scriptId:scope.scriptId,category:'ASSET_EDIT_BASELINE',status:'ACCEPTED'}).orderBy('createdAt','desc').orderBy('id','desc').limit(500);
 if(records.length===500)throw new PilotError('PILOT_BASELINE_LIMIT','基准历史过多，请联系管理人员',409);
 const seen=new Set<string>();return records.map((r:any)=>({...JSON.parse(r.content),version:r.id,confirmedAt:r.acceptedAt})).filter((r:any)=>{const key=r.canonicalKey+':'+r.role;if(seen.has(key))return false;seen.add(key);return true;});
}
export function suitableBaseline(rows:any[],canonicalKey:string,focus:string){
 const roles=focus==='FACE'?['FACE_HERO','GENERAL','FULL_BODY_FRONT']:focus==='BACK'?['FULL_BODY_BACK','GENERAL','FULL_BODY_FRONT']:['GENERAL','FULL_BODY_FRONT'];
 for(const role of roles){const row=rows.find(r=>r.canonicalKey===canonicalKey&&r.role===role);if(row)return row;}return null;
}
async function plan(trx:Knex.Transaction,data:z.infer<typeof baselineRequest>){
 if(!await trx('o_script').where({id:data.scriptId,projectId:data.projectId}).first())throw new PilotError('PILOT_SCOPE_INVALID','制作单元不存在',404);
 const asset=await trx('o_v04Asset').where({projectId:data.projectId,canonicalKey:data.canonicalKey,status:'ACTIVE'}).first();
 const attachment=await trx('o_v04AgentAttachment').where({id:data.attachmentId,projectId:data.projectId,scriptId:data.scriptId}).first();
 if(!asset||!attachment?.messageId)throw new PilotError('PILOT_REFERENCE_INVALID','图片或素材不属于当前对话和制作单元',409);
 const prior=(await baselinesInTransaction(trx,data)).find(r=>r.canonicalKey===data.canonicalKey&&r.role===data.role);
 const current={...data,sourceAssetRevision:asset.revision,sha256:attachment.sha256,mimeType:attachment.mimeType,originalName:attachment.originalName,previousVersion:prior?.version??null,sourceType:attachment.purpose==='GENERATED_CANDIDATE'?'GENERATED_CANDIDATE':'USER_UPLOAD',referenceResponsibility:data.role};
 return {current,assetName:asset.name,previewHash:hash(current),notice:'将这张图设为该素材后续改图的基准。旧图片保留，不改变已确认的文字设定、生产绑定或生产产物；这不是对图片与文字设定一致性的自动认证。'};
}
export async function previewImageBaseline(input:unknown){const data=baselineRequest.parse(input);const p=await q.transaction(trx=>plan(trx,data));const file=await getAgentAttachmentBytes(data.projectId,data.attachmentId);if(createHash('sha256').update(file.bytes).digest('hex')!==p.current.sha256)throw new PilotError('PILOT_SOURCE_STALE','图片内容已变化',409);return {...p,...data};}
export async function confirmImageBaseline(input:unknown){
 const data=baselineRequest.extend({previewHash:z.string().length(64)}).parse(input);
 const file=await getAgentAttachmentBytes(data.projectId,data.attachmentId),sha256=createHash('sha256').update(file.bytes).digest('hex'),meta=await sharp(file.bytes,{limitInputPixels:16000000}).metadata();
 return q.transaction(async trx=>{
  // Obtain SQLite write boundary before reading version/replay state.
  await trx('o_script').where({id:data.scriptId,projectId:data.projectId}).update({id:data.scriptId});
  const prior=await trx('o_v04Decision').where({...scopeSchema.parse({projectId:data.projectId,scriptId:data.scriptId}),category:'ASSET_EDIT_BASELINE',status:'ACCEPTED'}).whereRaw("json_extract(content, '$.previewHash') = ?",[data.previewHash]).first();
  if(prior){const value=JSON.parse(prior.content);if(value.canonicalKey!==data.canonicalKey||value.attachmentId!==data.attachmentId||value.role!==data.role||value.sha256!==sha256)throw new PilotError('PILOT_PREVIEW_STALE','确认请求已变化',409);const asset=await trx('o_v04Asset').where({projectId:data.projectId,canonicalKey:data.canonicalKey,status:'ACTIVE'}).first();if(!asset||asset.revision!==value.sourceAssetRevision)throw new PilotError('PILOT_PREVIEW_STALE','素材已变化',409);return {applied:true,replayed:true,version:prior.id};}
  const {previewHash:_hash,...request}=data;const p=await plan(trx,request);
  if(p.previewHash!==data.previewHash||p.current.sha256!==sha256)throw new PilotError('PILOT_PREVIEW_STALE','基准预览已过期，请重新查看',409);
  const id=randomUUID(),now=Date.now(),content={...p.current,previewHash:p.previewHash,width:meta.width,height:meta.height,format:meta.format};
  await trx('o_v04Decision').insert({id,projectId:data.projectId,scriptId:data.scriptId,category:'ASSET_EDIT_BASELINE',subjectType:'ASSET',subjectKey:data.canonicalKey,content:JSON.stringify(content),status:'ACCEPTED',sourceMessageIds:JSON.stringify([file.row.messageId]),supersedesDecisionId:p.current.previousVersion,createdAt:now,acceptedAt:now});
  const ref=await trx('o_v04AgentReference').where({projectId:data.projectId,scriptId:data.scriptId,attachmentId:data.attachmentId,targetType:'ASSET_BIBLE',targetKey:data.canonicalKey}).first();
  if(!ref)await trx('o_v04AgentReference').insert({id:randomUUID(),projectId:data.projectId,scriptId:data.scriptId,attachmentId:data.attachmentId,targetType:'ASSET_BIBLE',targetKey:data.canonicalKey,assetId:null,createdAt:now});
  return {applied:true,replayed:false,version:id};
 });
}
export async function listImageBaselines(input:unknown){const scope=scopeSchema.parse(input);return q.transaction(async trx=>{if(!await trx('o_script').where({id:scope.scriptId,projectId:scope.projectId}).first())throw new PilotError('PILOT_SCOPE_INVALID','制作单元不存在',404);const rows=await baselinesInTransaction(trx,scope);const assets=await trx('o_v04Asset').where({projectId:scope.projectId,status:'ACTIVE'}).whereIn('canonicalKey',rows.map(r=>r.canonicalKey));return rows.filter(r=>assets.some((a:any)=>a.canonicalKey===r.canonicalKey&&a.revision===r.sourceAssetRevision));});}
export async function recordCandidateBaseline(trx:Knex.Transaction,job:any,attachmentId:string,output:any,previewHash:string){
 const role=['FACE_HERO','FULL_BODY_FRONT','FULL_BODY_BACK','DETAIL_REFERENCE'].includes(job.executionPurpose)?job.executionPurpose:'GENERAL';
 const prior=(await baselinesInTransaction(trx,{projectId:job.projectId,scriptId:job.scriptId})).find(r=>r.canonicalKey===job.canonicalKey&&r.role===role);
 const id=randomUUID(),now=Date.now();
 await trx('o_v04Decision').insert({id,projectId:job.projectId,scriptId:job.scriptId,category:'ASSET_EDIT_BASELINE',subjectType:'ASSET',subjectKey:job.canonicalKey,status:'ACCEPTED',content:JSON.stringify({canonicalKey:job.canonicalKey,role,attachmentId,sha256:output.sha256,sourceAssetRevision:job.sourceAssetRevision,sourceType:'GENERATED_CANDIDATE',sourceJobId:job.id,sourceArtifactId:output.artifactId,width:output.width,height:output.height,previousVersion:prior?.version??null,previewHash}),sourceMessageIds:JSON.stringify([JSON.parse(job.inputSnapshotJson).userMessageId]),supersedesDecisionId:prior?.version??null,createdAt:now,acceptedAt:now});
}
